<?php 


// google setting
$client_id =Mage::getModel("sociallogin/google")->getGoogleClientID();; //your client id
$client_secret =Mage::getModel("sociallogin/google")->getGoogleClientSecret();; //your client secret
$redirect_uri = Mage::getModel("sociallogin/google")->getGoogleCallbackUrl();//"http://localhost/oauth2callback.php";

$scope = "https://www.googleapis.com/auth/userinfo.email"; //google scope to access
$state = "profile"; //optional
$google_loginUrl = sprintf("https://accounts.google.com/o/oauth2/auth?scope=%s&state=%s&redirect_uri=%s&response_type=code&client_id=%s",$scope,$state,$redirect_uri,$client_id);
?>

<button onclick="fblogin()" class="button btn btn-block btn-social btn-facebook">
    <span class="fa fa-facebook"></span> <?php echo $this->__("Sign in with Facebook") ?>
</button>

<button onclick="googlelogin()" class="button btn btn-block btn-social btn-google">
    <span class="fa fa-google-plus-square"></span> <?php echo $this->__("Sign in with Google") ?>
</button>

<script type="text/javascript">
	var  zeo_app_id= '<?php echo Mage::helper("sociallogin")->getFacebookAppID() ?>';
	var zeo_callback_url='<?php echo Mage::helper("sociallogin")->getFacebookCallbackUrl() ?>';
	if(zeo_app_id==""){
		alert("Please set up the App ID in System->configuration");
	}
    window.fbAsyncInit = function() {
        FB.init({
            appId      : zeo_app_id, // App ID
            status     : true, // check login status
            cookie     : true, // enable cookies to allow the server to access the session
            xfbml      : true  // parse XFBML
        });
    };

    // Load the SDK Asynchronously
    (function(d){
        var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement('script'); js.id = id; js.async = true;
        js.src = "//connect.facebook.net/en_US/all.js";
        ref.parentNode.insertBefore(js, ref);
    }(document));

    function greet(id){
        FB.api('/me', function(response) {
            var src = 'https://graph.facebook.com/'+id+'/picture';
            $$('.welcome-msg')[0].insert('<img height="20" src="'+src+'"/>');
        });
    }

    function fblogin(){
        
        try {
            FB.login(function(response) {
                if (response.status == 'connected') {
                    var url = zeo_callback_url;
                    document.location.href=url;
                } else if (response.status === 'not_authorized') {
                    alert('Please, approve our application');
                } else {
                    // user is not logged in
                    window.location.reload();
                }
            }, {scope:'email'});
        } catch (err) {
            fblogin();
        }
        return false;
    }
    // Google
    
    var google_url='<?php echo $google_loginUrl; ?>';
    function googlelogin(){
		document.location=google_url;
    }
</script>  